[package]
name = "hive-mcts"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
default = ["nn"]
nn = ["dep:ort"]

[dependencies]
hive-core.workspace = true
hive-uhp.workspace = true
hive-eval = { path = "../hive-eval" }
hive-nn = { path = "../hive-nn" }
rand.workspace = true
rand_chacha.workspace = true
ort = { version = "2.0.0-rc.10", features = ["coreml"], optional = true }
