#!/usr/bin/env python3
"""Generate paper/bibliography.md from docs/reading/ notes (plan ch. 27).

Two mandatory, disjoint sections: Bibliography (papers/theses/
proceedings) and Webographie (docs/sites/code, with consultation dates).
Only notes on disk enter — the no-invented-references rule is structural:
a source without a consulted note cannot be cited. purpose: outreach
notes are excluded.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NOTES = REPO / "docs" / "reading"


def parse_note(path):
    text = path.read_text()
    m = re.search(r"```yaml\n(.*?)```", text, re.S)
    if not m:
        return None
    fields = {}
    key = None
    for line in m.group(1).splitlines():
        km = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if km:
            key, val = km.group(1), km.group(2).strip()
            fields[key] = val.lstrip(">").strip()
        elif key and (line.startswith("  ") or line.startswith("\t")):
            fields[key] = (fields[key] + " " + line.strip()).strip()
    for k in ("citation", "venue_year", "version_doi", "classification",
              "purpose", "date_read"):
        fields.setdefault(k, "")
        fields[k] = fields[k].strip().strip('"')
    return fields


def main():
    bib, web = [], []
    for f in sorted(NOTES.glob("*.md")):
        if f.name == "matrix.md":
            continue
        n = parse_note(f)
        if not n or n["purpose"].startswith("outreach"):
            continue
        entry = (f"- {n['citation']} {n['venue_year']}. {n['version_doi']}"
                 f" *(note: `docs/reading/{f.name}`, read {n['date_read']})*")
        if n["classification"].startswith("webographie"):
            web.append(entry)
        else:
            bib.append(entry)
    out = ["# Bibliography and webographie (generated — plan ch. 27)",
           "",
           "Generated by `scripts/make_bibliography.py` from the reading "
           "notes; every entry was actually consulted (its note is the "
           "evidence) and no entry appears in both sections.",
           "", "## Bibliography", ""] + bib + ["", "## Webographie", ""] + web
    (REPO / "paper" / "bibliography.md").write_text("\n".join(out) + "\n")
    print(f"bibliography: {len(bib)} entries; webographie: {len(web)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
